version: '3'

services:
  dev:
    image: react-docker-example-dev
    build:
      context: ./
      dockerfile: Dockerfile.dev
    command: /bin/sleep infinity
    stop_grace_period: 1s
    working_dir: /assemble
    volumes:
      - ./:/assemble
    ports:
      - "3001:3000"
